# https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/

apiVersion: v1
kind: PersistentVolume
metadata:
  name: lh-kakfa-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lh-kafka-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

